### ISSUE TITLE
Breast Incompatible with Ad Astra

### ISSUE THREAD

**Issue by CeaAPI** [MayaqqDev/Estrogen#118]
**Ad Astra Version:** 1.15.18 (Latest)
**Create: Estrogen Version:** 4.2.10 (Latest)
**Minecraft Version:** 1.20.1
**Loader:** Fabric

Whenever wearing the Space Suit (and presumably other suits), the breast texture is just black and isn't actually the suit texture (image below).

![Image showing untextured, black breasts whilst wearing Space Suit](https://github.com/user-attachments/assets/8b240f9f-aeaf-4871-a865-bc4a9606c524)

(p.s. it truly does hurt my friends experience when they try to view my massive honkers :( )

**Comment by MayaqqDev** [comment]
Sadly the way breasts are done currently, well armor wise anyway, it's basically impossible, but we are working on a fix.

**Comment by CeaAPI** [comment]
Okay fire! I'm excited to see what y'all do :3

**Comment by nebulazorua** [comment]
> Sadly the way breasts are done currently, well armor wise anyway, it's basically impossible, but we are working on a fix.

I think it works with [Wildfire's Female Gender mod](https://github.com/WildfireRomeo/WildfireFemaleGenderMod) so that might clue in to what could fix it?

EDIT: it has a different issue when using the space suit, weirdly enough

(Would be nice to have some sort of compat between this mod and that mod, btw!)

**Comment by MayaqqDev** [comment]
Being currently worked on!
