### ISSUE TITLE
[BUG] Waystones visually reset chest

### ISSUE THREAD

**Issue by skyaur** [MayaqqDev/Estrogen#213]
When traveling between different dimensions using a waystone ([link](https://modrinth.com/mod/waystones)), the player's chest is visually reset (flat/isn't there).

Relogging or traveling through a nether portal restores the player's chest to what it should be.

**Comment by MayaqqDev** [comment]
Welcome to the world of traveling between dimensions resetting your attributes! Have a nice stay!

Anyway, its this bug here https://bugs.mojang.com/browse/MC-181604 You can try and look for a mod that fixes such bug, or suffer the consequences I guess.

Sorry about that

PS: You can just wait for create to update to newer versions, then estrogen and then it will be fixed :3
